[Variables]
ChangeWallpaper=
WallpaperDark=#Skinspath#\WP7\Gallery\Intro\wall1.jpg
WallpaperLight=#Skinspath#\WP7\Gallery\Intro\wall0.jpg
SunnriseSunset=1
MinutesHourMinute1=350
DarkMode1=0

_TwilightAM=--:--
_TwilightPM=--:--
_Rise=--:--
_Set=--:--
_Noon=--:--
_DayLength=0
_MaxAltitude=0
_Declination=0

;	_TimeZone, _DayLightSavingsTime, Latitude & Longitude for Copenhagen/Denmark (set your own values instead)
;	Set 12H=0/1 for 24/12 Hour time format
_TimeZone=0.0
12H=0
_DayLightSavingsTime=1

